on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: danfosscmsregistry.azurecr.io
        username: ${{ secrets.acr_danfosscmsregistry_username }}
        password: ${{ secrets.acr_danfosscmsregistry_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/github-integration" -f  "github-integration/Dockerfile" -t danfosscmsregistry.azurecr.io/zallytestcluster:${{ github.sha }}
        docker push danfosscmsregistry.azurecr.io/zallytestcluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_zallytestcluster_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep zallytestcluster903b | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace zallytestcluster903b`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: zallytestcluster903b
        container-registry-url: danfosscmsregistry.azurecr.io
        container-registry-username: ${{ secrets.acr_danfosscmsregistry_username }}
        container-registry-password: ${{ secrets.acr_danfosscmsregistry_password }}
        secret-name: zallytestcludockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: zallytestcluster903b
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
          manifests/ingress.yml
        images: |
          danfosscmsregistry.azurecr.io/zallytestcluster:${{ github.sha }}
        imagepullsecrets: |
          zallytestcludockerauth